---
deployment:
  tasks:
    - export APPPATH=	/home/trennguq/repositories/clinivent-ocr-api
    - /bin/mkdir -p $APPPATH/app

    - /bin/cp passenger_wsgi.py $APPPATH
    - /bin/cp requirements.txt $APPPATH

    - /bin/cp -R app/* $APPPATH/app

    - source /home/trennguq/virtualenv/myfastapiapp/3.11/bin/activate && pip install -r $APPPATH/requirements.txt

    - /usr/bin/touch /home/trennguq/tmp/restart.txt
